name: OrgaSegment2
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip=22.3.1
  - pip:
    - mlflow==2.14.1
    - scipy==1.13.1
    - ipython==8.18.1
    - matplotlib==3.8.2
    - pillow==11.0.0
    - natsort==8.4.0
    - opencv-python==4.8.1.78
    - scikit-image==0.22.0
    - numba==0.58.1
    - altair==4.0.0
    - torch==2.1.2
    - cellpose==3.1.0
    - streamlit==1.40.2
    - trackpy==0.6.4
    - pylint==3.3.1
